; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
lib_deps =
    adafruit/Adafruit NeoPixel @ ^1.10.0
    ESP32 BLE Arduino @ ^2.0.0

monitor_speed = 115200

; Kano Pixel Kit has sometimes troublesome reset circuitry.  Keep trying over and over!!!
upload_flags = 
    --connect-attempts=60

; ***** !IMPORTANT *************************************************************
; Note manual fix for <.pio/libdeps/esp32dev/ESP32-BLE-Gamepad/BleNUS.cpp>
;   MUST #include <Arduino.h> at top of file
; (fix after you get compilation errors of BleNUS.cpp within platformio project)
; ***** !IMPORTANT *************************************************************

; development only to differentiate devices connected
upload_port = COM10
monitor_port = COM10
